### ISSUE TITLE
ProArt PX13 support

### ISSUE THREAD

**Issue by duronald** [seerge/g-helper#2912]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The ProArt PX13 which is the newly released ROG Flow X13 successor does not work properly with Ghelper. 
Specifically, the performance modes do not align correctly with MyAsus and ProArt Creator Hub. 

The GPU Mode also is not working and constantly reports “iGPU +dGPU” with a stop GPU applications button.

### How to reproduce the bug?

1. Open Ghelper

### Logs

8/2/2024 7:09:38 PM: ------------
8/2/2024 7:09:38 PM: App launched: ProArt PX13 HN7306WU_HN7306WU :0.179.0.0en-US
8/2/2024 7:09:38 PM: Matrix control device was not found on your machine.
8/2/2024 7:09:39 PM: C:\ProgramData\ASUS\GameVisual doesn't exit
8/2/2024 7:09:39 PM: dGPU not found
8/2/2024 7:09:40 PM: CPU: 99999 - AMD Ryzen AI 9 HX 370 w/ Radeon 890M            - AMD64 Family 26 Model 36 Stepping 0
8/2/2024 7:09:40 PM: AutoSetting for Online
8/2/2024 7:09:40 PM: Optimization service is running
8/2/2024 7:09:40 PM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
8/2/2024 7:09:40 PM: Eco flag : -65536
8/2/2024 7:09:40 PM: Mux flag : -65536
8/2/2024 7:09:40 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 7:09:40 PM: \\?\DISPLAY#RMG0A8D#5&371d07e0&0&UID517#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 7:09:40 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor1
8/2/2024 7:09:40 PM: ATNA33AA08-0  HDR: False 10 0 False
8/2/2024 7:09:40 PM: Mode = 0 : OK
8/2/2024 7:09:40 PM: Init 19B6: 5D-B9
8/2/2024 7:09:40 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/2/2024 7:09:40 PM: Init 19B6: 5D-05-20-31-00-1A
8/2/2024 7:09:40 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
8/2/2024 7:09:40 PM: TUF_KB = 16712125 : 0
8/2/2024 7:09:40 PM: AuraMode: AuraStatic
8/2/2024 7:09:40 PM: USB 19B6: 5D-B3-00-00-FF-00-00-EB-00-00-FF-00-00-00-00-00-00
8/2/2024 7:09:40 PM: USB 19B6: 5D-B5-00-00-00
8/2/2024 7:09:40 PM: USB 19B6: 5D-B4
8/2/2024 7:09:40 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 7:09:40 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 7:09:40 PM: Touchpad status:1
8/2/2024 7:09:40 PM: Tablet: False Touchpad: True
8/2/2024 7:09:41 PM: Monitor Power On
8/2/2024 7:09:41 PM: Lid Open
8/2/2024 7:09:41 PM: TUF Brightness = 129 : OK
8/2/2024 7:09:41 PM: Lid 19B6: 5D-BA-C5-C4-01
8/2/2024 7:09:41 PM: TUF Brightness = 129 : OK
8/2/2024 7:09:41 PM: Auto 19B6: 5D-BA-C5-C4-01
8/2/2024 7:09:43 PM: ATNA33AA08-0  HDR: False 10 0 False
8/2/2024 7:09:45 PM: Latest version 0.179.0.0
8/2/2024 7:10:03 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 7:10:03 PM: Mode = 2 : OK
8/2/2024 7:10:04 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 7:10:04 PM: Mode = 0 : OK
8/2/2024 7:10:05 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 7:10:05 PM: Mode = 2 : OK
8/2/2024 7:10:06 PM: dGPU not found
8/2/2024 7:10:28 PM: Design Capacity: 73000mWh, Full Charge Capacity: 72299mWh, Health: 0.9903972602739726027397260274%
8/2/2024 7:10:36 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 7:10:36 PM: \\?\DISPLAY#RMG0A8D#5&371d07e0&0&UID517#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 7:10:36 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor1
8/2/2024 7:10:36 PM: Screen = 120Hz : -1
8/2/2024 7:10:36 PM: ATNA33AA08-0  HDR: False 10 0 False
8/2/2024 7:10:38 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 7:10:38 PM: \\?\DISPLAY#RMG0A8D#5&371d07e0&0&UID517#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 7:10:38 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor1
8/2/2024 7:10:38 PM: Screen = 120Hz : -1
8/2/2024 7:10:38 PM: ATNA33AA08-0  HDR: False 10 0 False
8/2/2024 7:10:38 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 7:10:38 PM: \\?\DISPLAY#RMG0A8D#5&371d07e0&0&UID517#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 7:10:38 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor1
8/2/2024 7:10:38 PM: Screen = 120Hz : -1
8/2/2024 7:10:38 PM: ATNA33AA08-0  HDR: False 10 0 False
8/2/2024 7:10:39 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 7:10:39 PM: \\?\DISPLAY#RMG0A8D#5&371d07e0&0&UID517#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 7:10:39 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor1
8/2/2024 7:10:39 PM: ATNA33AA08-0  HDR: False 10 0 False
8/2/2024 7:10:40 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 7:10:40 PM: \\?\DISPLAY#RMG0A8D#5&371d07e0&0&UID517#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 7:10:40 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor1
8/2/2024 7:10:40 PM: Screen = 120Hz : -1
8/2/2024 7:10:40 PM: ATNA33AA08-0  HDR: False 10 0 False
8/2/2024 10:16:39 PM: ------------
8/2/2024 10:16:39 PM: App launched: ProArt PX13 HN7306WU_HN7306WU :0.179.0.0en-US
8/2/2024 10:16:39 PM: Matrix control device was not found on your machine.
8/2/2024 10:16:41 PM: C:\ProgramData\ASUS\GameVisual doesn't exit
8/2/2024 10:16:41 PM: dGPU not found
8/2/2024 10:16:42 PM: CPU: 99999 - AMD Ryzen AI 9 HX 370 w/ Radeon 890M            - AMD64 Family 26 Model 36 Stepping 0
8/2/2024 10:16:42 PM: AutoSetting for Online
8/2/2024 10:16:42 PM: Optimization service is running
8/2/2024 10:16:42 PM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
8/2/2024 10:16:42 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 10:16:42 PM: Eco flag : -65536
8/2/2024 10:16:42 PM: Mux flag : -65536
8/2/2024 10:16:42 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 10:16:42 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 10:16:42 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 10:16:42 PM: Mode = 2 : OK
8/2/2024 10:16:42 PM: Init 19B6: 5D-B9
8/2/2024 10:16:42 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/2/2024 10:16:42 PM: Init 19B6: 5D-05-20-31-00-1A
8/2/2024 10:16:42 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
8/2/2024 10:16:42 PM: TUF_KB = 16712125 : 0
8/2/2024 10:16:42 PM: AuraMode: AuraStatic
8/2/2024 10:16:42 PM: USB 19B6: 5D-B3-00-00-FF-00-00-EB-00-00-FF-00-00-00-00-00-00
8/2/2024 10:16:42 PM: USB 19B6: 5D-B5-00-00-00
8/2/2024 10:16:42 PM: USB 19B6: 5D-B4
8/2/2024 10:16:42 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 10:16:42 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 10:16:42 PM: Touchpad status:1
8/2/2024 10:16:42 PM: Tablet: False Touchpad: True
8/2/2024 10:16:43 PM: Monitor Power On
8/2/2024 10:16:43 PM: Lid Open
8/2/2024 10:16:43 PM: TUF Brightness = 129 : OK
8/2/2024 10:16:43 PM: Lid 19B6: 5D-BA-C5-C4-01
8/2/2024 10:16:43 PM: TUF Brightness = 129 : OK
8/2/2024 10:16:43 PM: Auto 19B6: 5D-BA-C5-C4-01
8/2/2024 10:17:24 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 10:17:26 PM: Latest version 0.179.0.0
8/2/2024 10:17:29 PM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
8/2/2024 10:17:29 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:17:29 PM: Mode = 0 : OK
8/2/2024 10:17:32 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
8/2/2024 10:17:32 PM: Mode = 1 : OK
8/2/2024 10:17:35 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:17:35 PM: Mode = 0 : OK
8/2/2024 10:17:38 PM: dGPU not found
8/2/2024 10:17:45 PM: Mode = 0 : OK
8/2/2024 10:19:21 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
8/2/2024 10:19:21 PM: Mode = 1 : OK
8/2/2024 10:19:21 PM: dGPU not found
8/2/2024 10:19:37 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:19:37 PM: Mode = 0 : OK
8/2/2024 10:19:37 PM: dGPU not found
8/2/2024 10:19:38 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 10:19:38 PM: Mode = 2 : OK
8/2/2024 10:19:38 PM: dGPU not found
8/2/2024 10:19:45 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:19:45 PM: Mode = 0 : OK
8/2/2024 10:19:45 PM: dGPU not found
8/2/2024 10:20:09 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
8/2/2024 10:20:09 PM: Mode = 1 : OK
8/2/2024 10:20:09 PM: dGPU not found
8/2/2024 10:20:13 PM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
8/2/2024 10:20:13 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:20:13 PM: Mode = 0 : OK
8/2/2024 10:20:13 PM: dGPU not found
8/2/2024 10:29:37 PM: ------------
8/2/2024 10:29:37 PM: App launched: ProArt PX13 HN7306WU_HN7306WU :0.179.0.0en-US.
8/2/2024 10:29:37 PM: Matrix control device was not found on your machine.
8/2/2024 10:29:37 PM: C:\ProgramData\ASUS\GameVisual doesn't exit
8/2/2024 10:29:37 PM: dGPU not found
8/2/2024 10:29:38 PM: CPU: 99999 - AMD Ryzen AI 9 HX 370 w/ Radeon 890M            - AMD64 Family 26 Model 36 Stepping 0
8/2/2024 10:29:38 PM: AutoSetting for Online
8/2/2024 10:29:38 PM: Optimization service is running
8/2/2024 10:29:38 PM: Eco flag : -65536
8/2/2024 10:29:38 PM: Mux flag : -65536
8/2/2024 10:29:38 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 10:29:38 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 10:29:38 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 10:29:38 PM: Mode = 0 : OK
8/2/2024 10:29:38 PM: Init 19B6: 5D-B9
8/2/2024 10:29:38 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/2/2024 10:29:38 PM: Init 19B6: 5D-05-20-31-00-1A
8/2/2024 10:29:38 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
8/2/2024 10:29:38 PM: TUF_KB = 16712125 : 0
8/2/2024 10:29:38 PM: AuraMode: AuraStatic
8/2/2024 10:29:39 PM: USB 19B6: 5D-B3-00-00-FF-00-00-EB-00-00-FF-00-00-00-00-00-00
8/2/2024 10:29:39 PM: USB 19B6: 5D-B5-00-00-00
8/2/2024 10:29:39 PM: USB 19B6: 5D-B4
8/2/2024 10:29:39 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 10:29:39 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 10:29:39 PM: Touchpad status:1
8/2/2024 10:29:39 PM: Tablet: False Touchpad: True
8/2/2024 10:29:39 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 10:29:39 PM: Lid Open
8/2/2024 10:29:39 PM: Monitor Power On
8/2/2024 10:29:39 PM: TUF Brightness = 129 : OK
8/2/2024 10:29:39 PM: Lid 19B6: 5D-BA-C5-C4-01
8/2/2024 10:29:39 PM: TUF Brightness = 129 : OK
8/2/2024 10:29:39 PM: Auto 19B6: 5D-BA-C5-C4-01
8/2/2024 10:29:40 PM: Latest version 0.179.0.0
8/2/2024 10:29:47 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 10:29:47 PM: Mode = 2 : OK
8/2/2024 10:30:14 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:30:14 PM: Mode = 0 : OK
8/2/2024 10:30:19 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> ded574b5-45a0-4f42-8737-46345c09c238:OK
8/2/2024 10:30:19 PM: Mode = 1 : OK
8/2/2024 10:30:40 PM: dGPU not found
8/2/2024 10:30:47 PM: Mode = 1 : OK
8/2/2024 10:30:47 PM: dGPU not found
8/2/2024 10:30:48 PM: PowerLimit A3 = 50 : OK
8/2/2024 10:30:48 PM: PowerLimit A0 = 50 : OK
8/2/2024 10:30:48 PM: PowerLimit C1 = 50 : OK
8/2/2024 10:30:53 PM: Mode = 1 : OK
8/2/2024 10:30:53 PM: dGPU not found
8/2/2024 10:31:00 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 10:31:00 PM: Mode = 2 : OK
8/2/2024 10:31:01 PM: dGPU not found
8/2/2024 10:31:07 PM: dGPU not found
8/2/2024 10:31:12 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:31:13 PM: Mode = 0 : OK
8/2/2024 10:31:13 PM: dGPU not found
8/2/2024 10:31:18 PM: Mode = 0 : OK
8/2/2024 10:31:18 PM: dGPU not found
8/2/2024 10:31:19 PM: PowerLimit A3 = 50 : OK
8/2/2024 10:31:19 PM: PowerLimit A0 = 50 : OK
8/2/2024 10:31:19 PM: PowerLimit C1 = 50 : OK
8/2/2024 10:31:27 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 10:31:27 PM: Mode = 2 : OK
8/2/2024 10:31:32 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:31:32 PM: Mode = 0 : OK
8/2/2024 10:31:34 PM: PowerLimit A3 = 50 : OK
8/2/2024 10:31:34 PM: PowerLimit A0 = 50 : OK
8/2/2024 10:31:34 PM: PowerLimit C1 = 50 : OK
8/2/2024 10:38:40 PM: ------------
8/2/2024 10:38:40 PM: App launched: ProArt PX13 HN7306WU_HN7306WU :0.179.0.0en-US
8/2/2024 10:38:40 PM: Matrix control device was not found on your machine.
8/2/2024 10:38:41 PM: C:\ProgramData\ASUS\GameVisual doesn't exit
8/2/2024 10:38:41 PM: dGPU not found
8/2/2024 10:38:42 PM: CPU: 99999 - AMD Ryzen AI 9 HX 370 w/ Radeon 890M            - AMD64 Family 26 Model 36 Stepping 0
8/2/2024 10:38:42 PM: AutoSetting for Online
8/2/2024 10:38:42 PM: Optimization service is running
8/2/2024 10:38:42 PM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
8/2/2024 10:38:42 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 10:38:42 PM: Eco flag : -65536
8/2/2024 10:38:42 PM: Mux flag : -65536
8/2/2024 10:38:42 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 10:38:42 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 10:38:42 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 10:38:42 PM: Mode = 0 : OK
8/2/2024 10:38:42 PM: Init 19B6: 5D-B9
8/2/2024 10:38:42 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/2/2024 10:38:42 PM: Init 19B6: 5D-05-20-31-00-1A
8/2/2024 10:38:42 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
8/2/2024 10:38:42 PM: TUF_KB = 16712125 : 0
8/2/2024 10:38:42 PM: AuraMode: AuraStatic
8/2/2024 10:38:42 PM: USB 19B6: 5D-B3-00-00-FF-00-00-EB-00-00-FF-00-00-00-00-00-00
8/2/2024 10:38:42 PM: USB 19B6: 5D-B5-00-00-00
8/2/2024 10:38:42 PM: USB 19B6: 5D-B4
8/2/2024 10:38:42 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 10:38:42 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 10:38:42 PM: Touchpad status:1
8/2/2024 10:38:42 PM: Tablet: False Touchpad: True
8/2/2024 10:38:42 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 10:38:42 PM: Monitor Power On
8/2/2024 10:38:42 PM: Lid Open
8/2/2024 10:38:42 PM: TUF Brightness = 129 : OK
8/2/2024 10:38:42 PM: Lid 19B6: 5D-BA-C5-C4-01
8/2/2024 10:38:43 PM: TUF Brightness = 129 : OK
8/2/2024 10:38:43 PM: Auto 19B6: 5D-BA-C5-C4-01
8/2/2024 10:38:43 PM: Latest version 0.179.0.0
8/2/2024 10:38:43 PM: PowerLimit A3 = 50 : OK
8/2/2024 10:38:43 PM: PowerLimit A0 = 50 : OK
8/2/2024 10:38:43 PM: PowerLimit C1 = 50 : OK
8/2/2024 10:38:44 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 11:04:31 PM: ------------
8/2/2024 11:04:32 PM: App launched: ProArt PX13 HN7306WU_HN7306WU :0.179.0.0en-US
8/2/2024 11:04:32 PM: Matrix control device was not found on your machine.
8/2/2024 11:04:32 PM: C:\ProgramData\ASUS\GameVisual doesn't exit
8/2/2024 11:04:32 PM: dGPU not found
8/2/2024 11:04:33 PM: CPU: 99999 - AMD Ryzen AI 9 HX 370 w/ Radeon 890M            - AMD64 Family 26 Model 36 Stepping 0
8/2/2024 11:04:34 PM: AutoSetting for Online
8/2/2024 11:04:34 PM: Optimization service is running
8/2/2024 11:04:34 PM: Power Plan 381b4222-f694-41f0-9685-ff5bb260df2e:OK
8/2/2024 11:04:34 PM: Power Mode ded574b5-45a0-4f42-8737-46345c09c238 -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 11:04:34 PM: Eco flag : -65536
8/2/2024 11:04:34 PM: Mux flag : -65536
8/2/2024 11:04:34 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
8/2/2024 11:04:34 PM: \\?\DISPLAY#SDC41B0#5&371d07e0&0&UID512#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
8/2/2024 11:04:34 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 11:04:34 PM: Mode = 0 : OK
8/2/2024 11:04:34 PM: Init 19B6: 5D-B9
8/2/2024 11:04:34 PM: Init 19B6: 5D-41-53-55-53-20-54-65-63-68-2E-49-6E-63-2E
8/2/2024 11:04:34 PM: Init 19B6: 5D-05-20-31-00-1A
8/2/2024 11:04:34 PM: USB 19B6: 5D-BD-01-FF-1F-FF-FF-FF
8/2/2024 11:04:34 PM: TUF_KB = 16712125 : 0
8/2/2024 11:04:34 PM: AuraMode: AuraStatic
8/2/2024 11:04:34 PM: USB 19B6: 5D-B3-00-00-FF-00-00-EB-00-00-FF-00-00-00-00-00-00
8/2/2024 11:04:34 PM: USB 19B6: 5D-B5-00-00-00
8/2/2024 11:04:34 PM: USB 19B6: 5D-B4
8/2/2024 11:04:34 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 11:04:34 PM: TUF RGB = B4-00-FF-FF-FF-EB : 0
8/2/2024 11:04:34 PM: Touchpad status:1
8/2/2024 11:04:34 PM: Tablet: False Touchpad: True
8/2/2024 11:04:34 PM: ATNA33AA08-0  HDR: False 10 1 False
8/2/2024 11:04:34 PM: Monitor Power On
8/2/2024 11:04:34 PM: Lid Open
8/2/2024 11:04:34 PM: TUF Brightness = 129 : OK
8/2/2024 11:04:34 PM: Lid 19B6: 5D-BA-C5-C4-01
8/2/2024 11:04:35 PM: TUF Brightness = 129 : OK
8/2/2024 11:04:35 PM: Auto 19B6: 5D-BA-C5-C4-01
8/2/2024 11:04:35 PM: PowerLimit A3 = 50 : OK
8/2/2024 11:04:35 PM: PowerLimit A0 = 50 : OK
8/2/2024 11:04:35 PM: PowerLimit C1 = 50 : OK
8/2/2024 11:04:35 PM: Latest version 0.179.0.0
8/2/2024 11:05:41 PM: HID Device Event: Checking for new ASUS Mice

### Device and Model

ProArt PX13

### Armoury Crate

Uninstalled

**Comment by seerge** [comment]
@duronald hello,

What specifically is not aligning with performance modes? They seem to be accepted and switch properly

```
8/2/2024 7:10:03 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 7:10:03 PM: Mode = 2 : OK
8/2/2024 7:10:04 PM: Power Mode 961cc777-2547-4f9d-8174-7d86181b8a7a -> 00000000-0000-0000-0000-000000000000:OK
8/2/2024 7:10:04 PM: Mode = 0 : OK
8/2/2024 7:10:05 PM: Power Mode 00000000-0000-0000-0000-000000000000 -> 961cc777-2547-4f9d-8174-7d86181b8a7a:OK
8/2/2024 7:10:05 PM: Mode = 2 : OK
```

As for GPU, what options do you have in MyAsus or Procreate app? Cause from what i see atm your device doesn’t support disabling GPU, so app shows the only possible option :)

**Comment by duronald** [comment]
Hi @seerge ! Thank you for the help. The GPU targets in MyAsus are the normal ones - eco, standard and optimized. They all work identically as in the other Asus laptops but Ghelper does not see it for some reason. As for the power modes, although they “switch,” the wattages from the Ghelper modes when checked with HWinfo are different from the wattages of the MyAsus profiles.

**Comment by seerge** [comment]
@duronald can you check if last build in this thread works for GPU modes ? https://github.com/seerge/g-helper/issues/2847

**Comment by duronald** [comment]
Just tried the build, the GPU modes don’t show. When I set to performance mode in ProArt the wattage limit reported by HWINFO is generally 65W. However, when I use turbo in Ghelper the wattage gets set to 18W. Standard and silent also have similar issues.

**Comment by seerge** [comment]
@duronald can you post a screenshot of what are you measuring in hwinfo? Is it under load?

As for GPU mode - if build from that thread doesn’t show new modes, then I can only advise you to repeat all the steps I was asking in that thread to discover (one more?) endpoint responsible for GPU switching on your specific device

**Comment by duronald** [comment]
https://pastebin.com/QaHnSbGq Here is the DSDT dump. 

I’m currently testing out a few things with the power modes but there’s definitely something thing a little odd going on but will get back on that

**Comment by seerge** [comment]
@duronald hello, thanks for your effort. However this is not that I have asked :) Can you upload DSDT dump [as explained in Method **2** ](https://github.com/seerge/g-helper/issues/38)

**Comment by duronald** [comment]
[dsdt ProArt PX13.zip](https://github.com/user-attachments/files/16480670/dsdt.ProArt.PX13.zip)

Oops, I've atttached the zip from method 2 now.

**Comment by seerge** [comment]
@duronald ok, great, can you try this build ?

[GHelper.zip](https://github.com/user-attachments/files/16480683/GHelper.zip)

**Comment by duronald** [comment]
Thank you! Really appreciate the work everything seems to work. The power profiles seem to be working normally now as well. Not sure if that’s on my end or your end. Haven’t tested the battery charge limit but the keyboard lighting setting isn’t a valid one on this laptop but that’s probably a forgettable issue.

**Comment by seerge** [comment]
@duronald I haven't changed anything for profiles. To underline again - modes stored in BIOS. 

It could be that you had either battery saver power mode toggled (or may be any other windows-level changes into windows power plan), that somehow also restricted CPU performance.

The GPU endpoint for ProArt turned out to be exactly same as for Zenbooks and Vivobooks. The reason build from other thread did not work, cause I had enabled it only for models containing word "zenbook" or "vivobook". Not it will also include "proart".

Do I understand correctly that you don't have "Ultimate" mode in MyASUS ?

Is everything else working correctly now ?

**Comment by trailofsevens** [comment]
Thanks @seerge + @duronald for starting the thread. 
This has the GPU modes working on my PX13 now too which was the main thing I was keeping MyASUS for. So glad to see G-helper on this, appreciate all the work you do!

@duronald the charging limit worked on the main release already too, I limited mine to 95%

As for the keyboard, it has 3 brightness modes and that tracks to the G-helper slider correctly. I do see the keyboard fade up/down occasionally on starting but within the ASUS software there's no way to control this other than the 3 static brightness levels. So the options for "breathe" and "strobe" in G-helper don't do anything and can be ignored by anyone using this laptop it seems.

**Comment by trailofsevens** [comment]
The thing we seem to be missing with the above build vs the main build is any control over the GPU power limits in the Fans + Power settings. That was there in the main release, though I'm not sure if it worked or not. @duronald did you try that?

**Comment by duronald** [comment]
@seerge yes, there is no ultimate mode as this laptop has no dedicated mux switch.

**Comment by seerge** [comment]
@duronald @trailofsevens ok, great. Then I'm closing this as resolved :) Assuming everything else works.

Does MyASUS offer 4 performance modes btw (same as it happens for some Vivobooks) or only 3 ?

**Comment by duronald** [comment]
This laptop has 5 modes in the app - Windows Profile, Whisper, Standard, Performance, and manual. I think whisper to performance are the only relevant ones though. Does Ghelper have a toggle for 90hz as well? I believe this laptop screen can be modded to support 90hz.

**Comment by seerge** [comment]
@duronald "Windows" is usually `Balanced` (i.e. "Standard") profile, but with default windows power plan. G-Helper by default always uses that power plan, so it's same. "Manual" is `Turbo` (i.e. "Perormance" with custom power limits on top of it)

If you can set 90hz for display in windows - G-Helper would also show that. If you can't, then you can't ... :)

**Comment by duronald** [comment]
Sounds great thank you for all the help!

**Comment by seerge** [comment]
@duronald @trailofsevens changes included in https://github.com/seerge/g-helper/releases/tag/v0.182

**Comment by INVERATE** [comment]
Thank you for your efforts to make Ghelper working on those models !

The different modes are all working correctly, but I'm still having an issue when disabling the Asus services.
The function keys are not working anymore, and if I enable Fn-Lock, the keys are wrong and use a configuration for the ROG laptops. Maybe do not disable this particular service responsible of keyboard control, as it seems necessary for this laptop ?

**Comment by seerge** [comment]
@INVERATE i think it's just worth to explain here what specific FN-x hotkeys are not working, and explain what should they do :)

**Comment by seerge** [comment]
@duronald @INVERATE @trailofsevens 

I have checked screenshots of ProArt X13 keyboard, and it seem to be same as Vivobooks / Zenbooks. I also see that it seem to have a native fn-lock key (so no need for G-Helper to emulate it as it does for ROG/ TUF)

I have made some adjustments, and set hotkey / fn-lock handling for ProArt same as it is for Zenbooks, can you check this build (with Asus services stopped) and report what exactly is working and what's not

[GHelper.zip](https://github.com/user-attachments/files/16558434/GHelper.zip)

**Comment by seerge** [comment]
P.S. Also, since Zenbooks / Vivobooks have different color gamuts / visual modes approach comparing to ROG/TUF - can you check how exactly this section works on ProArt (currently it uses ROG/TUF method)

**Comment by trailofsevens** [comment]
@seerge My FN + function keys work as expected using your previous build (except the smiley face F8 but I'm not sure what it does) but I guess the question here is getting the FN lock to work?

I hadn't tested it prior to now, trying it with your previous build then @INVERATE is correct that it's mapped incorrectly. 
F1 = Mute (correct)
F2/F3 = Vol Down/Vol Up (incorrect, it reduces and increases the keyboard brightness)
F4 = Keyboard Brightness cycle (incorrect, it toggles the keyboard mode between breathe, strobe etc, which this doesn't support)

On your latest build above, the FN + Lock toggles the button in G-Helper the same as above (when using the shortcut for it FN + ESC) but the FN buttons don't do anything at all when FN lock is enabled (but still work using the FN + Function key)

Regarding colour modes - I don't have ProArt hub installed any more but I'll try and install it to check soon, its seems to have a whole different setup using a category under "Splendid" from memory.

**Comment by INVERATE** [comment]
@seerge With your latest version, the keys are now correctly mapped !
Except for F8 which is supposed to open the emoji window (like WIN + ; does), F11 didn't work the first time I have clicked on it, and F12 normally open ProArt Hub but could be remapped to open Ghelper.

For the visual modes, it seems like there are a  few available, see the picture I sent
![17232517944816669532929064082570](https://github.com/user-attachments/assets/1aa5e969-06fa-46ae-bd59-6342bfda4d83)

Normal, Vivid, Manual temperature, Eye care, and some other modes in a drop-down menu

**Comment by seerge** [comment]
@trailofsevens @INVERATE  Vivo and Zenbooks have native hardware level fn-lock. Looking at keyboard photos of ProartX13 - I assume here it should be also same. So do I understand correctly that in the latest build here `FN+Esc` toggles fn-lock correctly now ?

For regular keybindings, can you check in `%appdata%\GHelper\log.txt` what specific keycode \ WMI event does `FN + F8` generate ? I can map it to `WIN + ;` if needed.

For gamuts and **visual modes** - my question do they work currently in G-Helper ? Or only in MyASUS ?

**Comment by duronald** [comment]
Hi,

The color gamut modes only show in MyAsus right now.

**Comment by seerge** [comment]
@duronald ok, thanks, can you also check what WMI event does FN + F8 produce in a log ?

**Comment by duronald** [comment]
I’m out of town right now but can get back to it next week. @trailofsevens @INVERATE should be able to respond faster probably haha

**Comment by seerge** [comment]
This build should show Visual modes and Gamuts for your device. 

[GHelper.zip](https://github.com/user-attachments/files/16569215/GHelper.zip)

(FN+F8 still won't work as i need to know a keycode for it) :)

**Comment by INVERATE** [comment]
In the log.text file, F8 generate the line "Key: 126"

Also, for the keyboard, as said before, the settings for the different light modes are useless as there are not available for this laptop.

**Comment by INVERATE** [comment]
And color profile are working as expected! 💙 @seerge

**Comment by seerge** [comment]
@INVERATE ok, this build should also emit `WIN + ;` when you press `FN+F8` (keycode 126). But only if Asus services are stopped as otherwise they handle that. 

Please check if if this and fn-lock works correctly as well as visual modes / gamuts

As for backlight modes - is it a single white backlight that you have ? And no breathing / strobbing mode even ?

[GHelper.zip](https://github.com/user-attachments/files/16569254/GHelper.zip)

**Comment by INVERATE** [comment]
> @INVERATE ok, this build should also emit `WIN + ;` when you press `FN+F8` (keycode 126). But only if Asus services are stopped as otherwise they handle that.
> 
> Please check if this and fn-lock works correctly as well as visual modes / gamuts
> 
> As for backlight modes - is it a single white backlight that you have ? And no breathing / strobbing mode even ?
> 
> [GHelper.zip](https://github.com/user-attachments/files/16569254/GHelper.zip)

F8 is working 
Fn-Lock has no impact on the use of the function keys (wether or not enabled, the Functions F1 to F12 can only be used with FN key clicked)
F12 normally open ProArt Hub but has now no use
Visual modes are working

There is only a full backlight for the keyboard, no animation

**Comment by seerge** [comment]
@INVERATE 

>Fn-Lock has no impact on the use of the function keys (wether or not enabled, the Functions F1 to F12 can only be used with FN key clicked)
 
How do you activate FN-Lock ? Via FN+ESC ? or via FN+C ?

>F12 normally open ProArt Hub but has now no use

What keycode does it produce in the log ?

**Comment by INVERATE** [comment]
@seerge 
FN-Lock with FN+ESC

F12 produces 139

**Comment by seerge** [comment]
@INVERATE so FN+ESC does nothing ? Can you also check what does FN+Esc produce in the log  ?

**Comment by INVERATE** [comment]
> @INVERATE so FN+ESC does nothing ? Can you also check what does FN+Esc produce in the log ?

The number generated for FN-LOCK is 78

**Comment by INVERATE** [comment]
![1723288258768890103875944983458](https://github.com/user-attachments/assets/4b85929c-e5f8-4d16-8584-d26b63a3a81a)

**Comment by seerge** [comment]
@INVERATE ok, but then it should be already handled (as you see app runs a hardware toggle for it).

How does it work without G-Helper ? (with MyASUS + Asus services running) ? Do F1-F12 run their functions without FN ?

**Comment by seerge** [comment]
P.S. Can you try to toggle FN-Lock in G-Helper using just UI (i.e. click on a `FN-LOCK` button in the main window) and see if it makes a difference ?

**Comment by INVERATE** [comment]
With the Asus services, this how it shows
![17232888884287705138050788312363](https://github.com/user-attachments/assets/84ab2141-764f-4fe2-a72c-aa832dbb74f7)
![17232889119917507257026438375155](https://github.com/user-attachments/assets/0df321ae-b3cc-489a-aa6b-5ef68dc53891)

As expected, there is a mode where we don't have to clicked on FN to use the function keys or "quick access" alternatively

**Comment by INVERATE** [comment]
> P.S. Can you try to toggle FN-Lock in G-Helper using just UI (i.e. click on a `FN-LOCK` button in the main window) and see if it makes a difference ?

No difference whatsoever

**Comment by seerge** [comment]
@INVERATE ok, can you do a following test then

1. With Asus services running - Toggle FN-Lock on (so you see native notification)
2. Open G-Helper 
3. Then try to press F4, F8 and F12 directly (without FN) and check if Key 126, Key 139, etc is being logged in app log ?

**Comment by INVERATE** [comment]
@seerge 

When in the normale function keys mode with Asus services, F4 F8 F12 are not registered in the log

When Fn-Lock is enabled by Asus services, WMI events are registered (199, 126, 139 respectively). But the toggle Fn-Lock in the UI is not active

**Comment by seerge** [comment]
@INVERATE ok, thanks for confirming. Then it looks like FN-Lock is still firmware / hardware based (as keys start emitting events when it's ON). But it's being toggled in some other way ...

Can you make a DSDT dump and upload it as explained in [Method 2 here ](https://github.com/seerge/g-helper/issues/38) ? 

Thanks for helping

**Comment by INVERATE** [comment]
If that the method, there is no dsdt.dat created,  I'm sorry...🫤 There are others .dat files, but not this one

> 
> Crate a dump and upload it here (as suggested by @vddCore )
> 
> Download ACPICA tools. Extract into some folder.
> 
> Open that folder in powershell and run ./acpidump.exe -b to dump them all to .dat files. They'll be placed in the location you ran the tool from.
> 
> Then run ./iasl.exe dsdt.dat and the decompiled ACPI table will be created as dsdt.dsl. Zip it and upload here.

**Comment by seerge** [comment]
@INVERATE ok, nevermind, I have noticed that other user has already uploaded DSDT dump in this thread above.

What is strange that I see that endpoint responsible for FN-Lock toggle (on other devices) is available here and seem to do a toggle
````
                    If ((IIA0 == 0x00100023))
                    {
                        If ((IIA1 == One))
                        {
                            Local0 = 0x08
                        }
                        ElseIf ((IIA1 == Zero))
                        {
                            Local0 = 0x04
                        }

                        Local0 = (KFSK | Local0)
                        ^^PCI0.SBRG.EC0.ST9E (0x3C, 0xFF, Local0)
                        Return (One)
                    }
````

It could be that FN-Lock is inverted here tho ... can you check if this build makes any difference ?

[GHelper.zip](https://github.com/user-attachments/files/16569550/GHelper.zip)

**Comment by seerge** [comment]
Alternatively, if it doesn't help there is one more idea

1. Quit G-Helper, 
2. Open `%appdata%\GHelper\config.json` and add following line to the beginning of the file

```
"debug": 1,
```

3. Save it and start G-Helper again.

4.Open `Extra` and click on newly appeared `Zoomglass icon`, it will run a scan and open a log result with it
5. Toggle FN-Lock via asus services, and run a scan from `Extra` agian

Upload results of both scans here ... :)

**Comment by INVERATE** [comment]
@seerge 
I will try what you told me. I'll keep you posted.

I think the issue is that Ghelper Fn-Lock doesn't do anything.
Only the Asus services do. If I disable Fn-Lock via Asus and then stop them, Ghelper Fn-Lock has no effect when I enable it. It stays the way Asus set it

**Comment by INVERATE** [comment]
@seerge 
```
Scan started 10/08/2024 14:27:30
00010001: 30000 (196608)
00010011: 20001 (131073)
00010013: 20001 (131073)
00020011: 40002 (262146)
00020012: 40002 (262146)
00020013: 40000 (262144)
00020014: 40000 (262144)
00020015: 40002 (262146)
00020016: 40002 (262146)
00040015: 40000 (262144)
00050002: 0000 (0)
00050021: 1F0000 (2031616)
0005002F: 0001 (1)
00050033: 0000 (0)
00050042: 0036 (54)
00060026: 0000 (0)
00060059: 0000 (0)
00060062: 0000 (0)
0006006D: 0000 (0)
00060078: 300000 (3145728)
000600C4: 0005 (5)
00090030: 0010 (16)
00100023: 0002 (2)
00100051: 0001 (1)
00100063: 0001 (1)
00100071: 0041 (65)
00110013: 0000 (0)
00110014: 0000 (0)
00110024: 3532312F (892481839)
00110025: 3532312F (892481839)
00120057: 1880000 (25690112)
00120059: 0000 (0)
00120061: 20000 (131072)
0012006C: 0000 (0)
0012006D: 0000 (0)
00120070: 0000 (0)
00120075: 0003 (3)
00120078: 0000 (0)
0012008E: 0001 (1)
0012008F: 0000 (0)
00120098: 0000 (0)
00120099: 0037 (55)
0012009A: 000A (10)
001200A0: 0000 (0)
001200A3: 0000 (0)
001200C0: 0000 (0)
001200C1: 0000 (0)
001200C2: 0000 (0)
00130041: 0000 (0)
---------------------
Scan started 10/08/2024 14:28:09
00010001: 30000 (196608)
00010011: 20001 (131073)
00010013: 20001 (131073)
00020011: 40002 (262146)
00020012: 40002 (262146)
00020013: 40000 (262144)
00020014: 40000 (262144)
00020015: 40002 (262146)
00020016: 40002 (262146)
00040015: 40000 (262144)
00050002: 0000 (0)
00050021: 1F0000 (2031616)
0005002F: 0001 (1)
00050033: 0000 (0)
00050042: 0036 (54)
00060026: 0000 (0)
00060059: 0000 (0)
00060062: 0000 (0)
0006006D: 0000 (0)
00060078: 300000 (3145728)
000600C4: 0005 (5)
00090030: 0010 (16)
00100023: 0002 (2)
00100051: 0001 (1)
00100063: 0001 (1)
00100071: 0041 (65)
00110013: 0000 (0)
00110014: 0000 (0)
00110024: 3532312F (892481839)
00110025: 3532312F (892481839)
00120057: 1880000 (25690112)
00120059: 0000 (0)
00120061: 20000 (131072)
0012006C: 0000 (0)
0012006D: 0000 (0)
00120070: 0000 (0)
00120075: 0003 (3)
00120078: 0000 (0)
0012008E: 0001 (1)
0012008F: 0000 (0)
00120098: 0000 (0)
00120099: 0037 (55)
0012009A: 000A (10)
001200A0: 0000 (0)
001200A3: 0000 (0)
001200C0: 0000 (0)
001200C1: 0000 (0)
001200C2: 0000 (0)
00130041: 0000 (0)
---------------------
```

**Comment by seerge** [comment]
@INVERATE ok, thanks. Both scans seem to be absolutely same, was FN-Lock toggled in Asus services in between running them ? (ideas is to compare outcome with it's being ON and OFF)

**Comment by INVERATE** [comment]
Yes, Fn-Lock was activated in the second one

**Comment by seerge** [comment]
@INVERATE ok, does FN-Lock stay ON if you would enable it first and then stop asus services (via G-Helper) ?

**Comment by INVERATE** [comment]
Yes
As I said, the FN-LOCK button in Ghelper doesn't change anything, only Asus services do

**Comment by seerge** [comment]
@INVERATE it's clear that in G-Helper it's not working atm :) my question was - if FN-Lock keeps working if it was enabled via asus services and then services themselves are stopped (i.e. if it needs the services to run to keep working)

@INVERATE 

There is one more way to try to check how asus services toggle it, but it requires quite a lot of work

If you want - you can follow this guild
https://github.com/seerge/g-helper/wiki/_ACPI-Monitoring-and-Debugging

With the only difference, is that you need to catch what kind of event happens when you toggle FN-Lock

**Comment by INVERATE** [comment]
> @INVERATE it's clear that in G-Helper it's not working atm :) my question was - if FN-Lock keeps working if it was enabled via asus services and then services themselves are stopped (i.e. if it needs the services to run to keep working)

Yeah, it is working fine without Asus services. Once activated it stays on, that sufficient for me. It is not a big deal for me, as I don't use the function keys so much.

Maybe the other members of this discussion will try to follow the guide you've sent.

Thanks for your help so far, and for the amazing work you've made on this software

**Comment by seerge** [comment]
@INVERATE just to double check something, can you check if this build of G-Helper makes any difference for fn-lock?

[GHelper.zip](https://github.com/user-attachments/files/16569943/GHelper.zip)

**Comment by trailofsevens** [comment]
@seerge Not sure if this helps or adds more confusion but the [first build](https://github.com/seerge/g-helper/issues/2912#issuecomment-2266708368) you provided to me FN-Lock works perfectly in-sync with G-Helper's FN-Lock button, and the function buttons worked without holding FN (but they were just mapped incorrectly)

In the latest build (visual modes work, that's fantastic thanks!, I wasn't even sure that was covered/possible by G-Helper) the FN + ESC toggles the button in G-Helper, but now the function keys don't do anything.

**Comment by seerge** [comment]
@trailofsevens the reason it worked is cause ROG/TUF models don't have a native fn-lock, and what G-Helper does is just registers F1-F11 as own hotkeys in windows and runs corresponding actions when they are pressed.

While Vivo / Zenbooks and ProArt (apparently) has a native fn-lock. The one i'm trying to toggle. It just seems that on this specific model standard toggle working for Vivo and Zenbooks is not working by some reason.

And I need someone to catch actual command asus service sends to firmware to toggle it using this guide
https://github.com/seerge/g-helper/wiki/_ACPI-Monitoring-and-Debugging

**Comment by trailofsevens** [comment]
@seerge Thanks for the explanation, that makes sense!

Here's the data, I reinstalled ProArt Hub and enabled all the ASUS services just to make sure I catch it. I toggled it on first, then off. 
[irpmon_fnlock_asuspx13.log](https://github.com/user-attachments/files/16570633/irpmon_fnlock_asuspx13.log)

As a side note (that's not urgent), is there any way to bind custom "Fans + Power" profiles/curves to the right click options in the G-Helper system tray? Since I'm using some custom profiles for my own light/eco mode with a very relaxed fan curve, as well as my own performance mode with a more gradual curve. Since the default PX13 profiles are quite aggressive with their tdp and fan curves.

**Comment by seerge** [comment]
@trailofsevens ok, great, thanks! :)

It's interesting, cause the only command it emits .. its just a command for FN-Lock hotkey itself (so it's same for ON and for OFF)

Can you check this build (with asus services stopped) ?

[GHelper.zip](https://github.com/user-attachments/files/16570657/GHelper.zip)

**Comment by trailofsevens** [comment]
@seerge No problem! Just tested it, and it strobes/repeats the toggle in a loop, so once I press it, it'll keep firing on/off/on/off until I exit G-Helper. Which I guess makes sense with both commands being the same for on/off like you said, not sure how asus are handling it differently then.

Regarding the extra modes - thanks, makes sense! I wasn't sure if there was a difference between the in-built vs extra but it seems obvious now you've said it haha. I'll do that 👍

**Comment by seerge** [comment]
@trailofsevens ok, thanks for checking. Then it's a complete mystery on how it toggles it then. 

I can try to adapt a software fn-lock for this keyboard then
![image](https://github.com/user-attachments/assets/cbf91f32-f8b0-4da3-8c12-8b180c95cee0)

**Comment by trailofsevens** [comment]
@seerge Let me know if there's anything else I can check since I should be around for the next few hours + I still have the IRPMon installed etc. 

But yeah if there's no other routes to investigate - then it functioning similar to ROG/TUF (where FN + F1 doesn't work when locked) would still be great :)

**Comment by seerge** [comment]
@trailofsevens @INVERATE @duronald 

Ok, since it seem to be unclear how exactly hardware fn-lock gets toggled on this ProArt device, I have just replaced it with a software emulation (same as app does it for ROG / TUF)

Please check this build. Keep in mind that F12 can't be covered with a software fn-lock as it's reserved by windows.
[GHelper.zip](https://github.com/user-attachments/files/16573120/GHelper.zip)

**Comment by trailofsevens** [comment]
@seerge Thanks! All the function buttons are mapped correctly on my keyboard. FN-Lock toggling as expected with FN+ESC too.

**Comment by seerge** [comment]
@trailofsevens @INVERATE @duronald

I think I have found how hardware toggle for FN-Lock works on your device (discovered it for ProArt 16)

Can you try this build and check if FN-lock works here (and post a log from it)

[GHelper.zip](https://github.com/user-attachments/files/16727923/GHelper.zip)

THanks

**Comment by seerge** [comment]
@trailofsevens great, thanks for confirming. I don't need a logs since it works and someone else has also confirmed same.

It turned out that communication with keyboard goes over USB (same as on ROG models) and not over ACPI (so IRPMmon could not catch that) :)

**Comment by seerge** [comment]
@trailofsevens ah, can you also check if FN-lock works as it should or if it's inverted [as people using ProArt 16 report here](https://github.com/seerge/g-helper/issues/3012) ?

**Comment by trailofsevens** [comment]
Currently it works like:
FN-Lock on = F5 refresh pages
FN-Lock off = F5 decreases screen brightness.

I assumed that was the correct functionality, as in it locks the FN buttons to behave just like FN 1-2-3 etc?

**Comment by seerge** [comment]
@trailofsevens i think it's also inverted.

Default state is FN-Lock being OFF, and then F5 should do F5.

When FN-Lock is ON - it "kind of" keeps FN button permanently pressed and makes F5 do it's secondary function (i.e. adjust brightness)

**Comment by trailofsevens** [comment]
@seerge Ah I see, makes sense when put that way! In that case it does seem to be inverted then, same as the P16 reports.

**Comment by duronald** [comment]
Hi,

yes, FN lock is definitely inverted haha. Also, is it possible to hide the keyboard lighting options like breathe if the laptop doesn’t support it?

**Comment by seerge** [comment]
@duronald but as I understand you can't change neither modes nor color ? So whole section makes no sense in your case ?

**Comment by duronald** [comment]
@seerge Yes that’s correct. The only thing we can change is the brightness which every laptop can do to my knowledge

**Comment by seerge** [comment]
@duronald this build should hide unsupported backlight modes (literally whole backlight section) for X13 and I have also added Flicker Free dimming control (since it's OLED) model

[GHelper.zip](https://github.com/user-attachments/files/16737590/GHelper.zip)

**Comment by INVERATE** [comment]
hi @sergee
sorry to open this issue again. I still have a bug o the asus PX13
The FN-lock toggle seems not to be active the first time I use it when powering on the laptop, even if the button in Ghelper is showing ON. I need to do FN+ESC two times to enable it again. It is not a big deal, but if you could do something that would be amazing !
thanks

**Comment by seerge** [comment]
@INVERATE can you post a log from the app since starting a laptop ?

**Comment by TianruiBai** [comment]
Hi, @seerge. I encountered some issues with G-Helper. First problem is the latest release mapped my F1-F12 function keys shortcut incorrectly. However, the build in the reply I quoted works.

> @trailofsevens @INVERATE @duronald
> 
> Ok, since it seem to be unclear how exactly hardware fn-lock gets toggled on this ProArt device, I have just replaced it with a software emulation (same as app does it for ROG / TUF)
> 
> Please check this build. Keep in mind that F12 can't be covered with a software fn-lock as it's reserved by windows. [GHelper.zip](https://github.com/user-attachments/files/16573120/GHelper.zip)

 Second problem is toggle camera is not working,  windows response the camera is block by a shutter or disabled by button. (I'm not sure this problem caused by ASUS, since function keys mapped incorrectly, and camera been disabled occurred after I reinstall windows).
Also, here is the dsdt I dump.
[dsdt.zip](https://github.com/user-attachments/files/17334770/dsdt.zip)

Thanks for supporting such latest machine

**Comment by seerge** [comment]
@TianruiBai hello, what laptop model do you have , upload full log from the app, as PX13 has hardware fn-lock (it's not handled by the app).

For camera toggle to work - you need to run it as admin

**Comment by TianruiBai** [comment]
@seerge No problems!. The model I have is HN7306WU, I know the PX13 has a hardware fn-lock (which currently is disabled in BIOS). I have confirm that I run G-Helper under admin.
[log.txt](https://github.com/user-attachments/files/17334912/log.txt)

**Comment by seerge** [comment]
@TianruiBai ok, from the log i see that app toggles fn-lock on hardware level for this model (via USB command) as it should in the latest releases

```
2024/10/10 16:46:50: Key: 158
2024/10/10 16:46:50: FnLock = 1 : OK
2024/10/10 16:46:50: USB FnLock 19B6|64: 5A-D0-4E-00
2024/10/10 16:46:50: Key: 158
2024/10/10 16:46:50: FnLock = 0 : OK
2024/10/10 16:46:50: USB FnLock 19B6|64: 5A-D0-4E-01
```

So then G-Helper is not "mapping" keys, but hardware does. What exactly is not mapped correctly ? If you have some hardware toggle for FN-Lock in BIOS, i think you need to enable it too ...
---

As for camera toggle, it toggles this setting in windows (by using a registry toggle), as was initially discussed in this issue https://github.com/seerge/g-helper/issues/2060
![image](https://github.com/user-attachments/assets/2655cdbd-c520-4452-9907-1f5ba7eb4016)

**Comment by angelaki** [comment]
Hey, trying my luck here since ASUS itself is a horrible source for information. As far as I know, the PX13 does not support dGPU inly / has no MUX / Advanced Optimus etc.. Is this true? Git this device trying to run it with a VR headset (what doesnt work without). Seams so untrue ... Such a great device and they saved these ... Like 50 pennies?! Not even for VR, but the device could be pretty much faster with a native connection!

**Comment by seerge** [comment]
@angelaki yes, it doesn't support Ultimate (hardware MUX switch) mode. But you still have Advanced Optimus that can route internal display to nvidia GPU

**Comment by angelaki** [comment]
@seerge thank you for your fast response! And can this somehow route dGPU to USB (DP-Alt Mode)? Tried several things now but no luck so far.

Wouldnt Advanced Optimus mean I could disable the iGPU?

**Comment by seerge** [comment]
@angelaki usually some ports (like HDMI or right-USB-C) are linked to dGPU, some (left usb-C) to iGPU.

Advanced optimus does not affect that. It can't disable iGPU, but it routes internal screen to dGPU to make things run faster on it.

**Comment by angelaki** [comment]
@seerge but that's just for the internal screen? As far as I can tell, it seams like none of the ports is directly connected to the dGPU. Only the HDMI Port but I need a DP for the VIVE Pro 2.

**Comment by BaiTian6641** [comment]
> [@TianruiBai](https://github.com/TianruiBai) ok, from the log i see that app toggles fn-lock on hardware level for this model (via USB command) as it should in the latest releases
> 
> ```
> 2024/10/10 16:46:50: Key: 158
> 2024/10/10 16:46:50: FnLock = 1 : OK
> 2024/10/10 16:46:50: USB FnLock 19B6|64: 5A-D0-4E-00
> 2024/10/10 16:46:50: Key: 158
> 2024/10/10 16:46:50: FnLock = 0 : OK
> 2024/10/10 16:46:50: USB FnLock 19B6|64: 5A-D0-4E-01
> ```
> 
> So then G-Helper is not "mapping" keys, but hardware does. What exactly is not mapped correctly ? If you have some hardware toggle for FN-Lock in BIOS, i think you need to enable it too ...
> 
> As for camera toggle, it toggles this setting in windows (by using a registry toggle), as was initially discussed in this issue [#2060](https://github.com/seerge/g-helper/issues/2060) ![image](https://github.com/user-attachments/assets/2655cdbd-c520-4452-9907-1f5ba7eb4016)

Hi, I'm back on this question. The problem still occurred here, even if I tried to reset BIOS, changing setting of FN-Lock, reinstall drivers and software. Camera seem like stuck at here, no way to inform system to turn off camera shutter. Other functions from g-helper are working except this one. I guessed ASUS probably messed up with control interface driver.
This is so weird, even if I try to do cloud recovery in BIOS, the keys are still messed up.
Fn+Esc key lock no longer working since ASUS software messed up, basically it is not available, even I change setting in myASUS.
